# Site settings
title: Nothing's Impossible
email: alex@kobachi.jp
description: >- 
  Even the stars look brighter tonight, nothing's impossible.
baseurl: "" 
url: "https://kobachi.jp"
# twitter_username: za_kobachi
github_username: za-kobachi
linkedin_username: kobachi

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
